name = "rachel-levy-uk"
main = "worker.js"
compatibility_date = "2024-05-01"

assets = { directory = "./output" }

route = "rachellevy.uk/*"
zone_id = "34b5cacfcbf084ad1d81a286fef18968"

not_found_handling = "404-page"
# html_handling = "auto-trailing-slash"
