name = "rachel-levy-uk"
main = "worker.js"
compatibility_date = "2024-05-01"

assets = { directory = "./output" }

route = "rachellevy.org.uk/*"
zone_id = "c31b4fc12a1a9f3ea20c02e0ddbf08da"

not_found_handling = "404-page"
# html_handling = "auto-trailing-slash"
