name: Deploy to Cloudflare Workers

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Stork Search version 1.6.0
        run: |
          wget -O stork wget https://files.stork-search.net/releases/v1.6.0/stork-ubuntu-20-04
          chmod +x stork
          sudo mv stork /usr/local/bin/stork
          stork --version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install all dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Pelican site
        run: pelican content -o output -s pelicanconf.py

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare with Wrangler
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          wrangler deploy \
            --minify \
            --outdir wrangler-build
